// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/oauth_client_repository.go

// Package repository_mock is a generated GoMock package.
package repository_mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	echo "github.com/labstack/echo/v4"
	dto "github.com/ucho456job/lgtmeme/internal/dto"
	model "github.com/ucho456job/lgtmeme/internal/model"
)

// MockOauthClientRepository is a mock of OauthClientRepository interface.
type MockOauthClientRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOauthClientRepositoryMockRecorder
}

// MockOauthClientRepositoryMockRecorder is the mock recorder for MockOauthClientRepository.
type MockOauthClientRepositoryMockRecorder struct {
	mock *MockOauthClientRepository
}

// NewMockOauthClientRepository creates a new mock instance.
func NewMockOauthClientRepository(ctrl *gomock.Controller) *MockOauthClientRepository {
	mock := &MockOauthClientRepository{ctrl: ctrl}
	mock.recorder = &MockOauthClientRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOauthClientRepository) EXPECT() *MockOauthClientRepositoryMockRecorder {
	return m.recorder
}

// FirstByClientID mocks base method.
func (m *MockOauthClientRepository) FirstByClientID(c echo.Context, clientID uuid.UUID, columns []string) (*model.OauthClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstByClientID", c, clientID, columns)
	ret0, _ := ret[0].(*model.OauthClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FirstByClientID indicates an expected call of FirstByClientID.
func (mr *MockOauthClientRepositoryMockRecorder) FirstByClientID(c, clientID, columns interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstByClientID", reflect.TypeOf((*MockOauthClientRepository)(nil).FirstByClientID), c, clientID, columns)
}

// IsValidOAuthClient mocks base method.
func (m *MockOauthClientRepository) IsValidOAuthClient(c echo.Context, q dto.AuthzQuery) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsValidOAuthClient", c, q)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsValidOAuthClient indicates an expected call of IsValidOAuthClient.
func (mr *MockOauthClientRepositoryMockRecorder) IsValidOAuthClient(c, q interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsValidOAuthClient", reflect.TypeOf((*MockOauthClientRepository)(nil).IsValidOAuthClient), c, q)
}
