version: '3.8'

services:
  postgres:
    container_name: my_authn_authz_postgres
    image: postgres:15.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TZ}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - default
  redis:
    container_name: my_authn_authz_redis
    image: redis:6.2
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - default